#!/bin/bash

# Simple Production Deployment Guide
# This script provides step-by-step instructions for deploying the backend

echo "🚀 Production Backend Deployment Guide"
echo "======================================"
echo ""

echo "📋 Prerequisites:"
echo "1. Google Cloud account with billing enabled"
echo "2. Firebase project: ai-agent-hub-web-portal-79fb0"
echo "3. Node.js 18+ installed locally"
echo ""

echo "🔧 Option 1: Deploy to Google Cloud Run (Recommended)"
echo "-----------------------------------------------------"
echo "1. Install Google Cloud CLI:"
echo "   curl https://sdk.cloud.google.com | bash"
echo "   exec -l $SHELL"
echo ""
echo "2. Authenticate and set project:"
echo "   gcloud auth login"
echo "   gcloud config set project ai-agent-hub-web-portal-79fb0"
echo ""
echo "3. Enable required APIs:"
echo "   gcloud services enable cloudbuild.googleapis.com"
echo "   gcloud services enable run.googleapis.com"
echo "   gcloud services enable containerregistry.googleapis.com"
echo ""
echo "4. Build and deploy:"
echo "   gcloud builds submit --tag gcr.io/ai-agent-hub-web-portal-79fb0/agent-backend"
echo "   gcloud run deploy agent-backend --image gcr.io/ai-agent-hub-web-portal-79fb0/agent-backend --platform managed --region us-central1 --allow-unauthenticated --port 8080"
echo ""

echo "🔧 Option 2: Deploy to Firebase Functions"
echo "----------------------------------------"
echo "1. Install Firebase CLI:"
echo "   npm install -g firebase-tools"
echo ""
echo "2. Login to Firebase:"
echo "   firebase login"
echo ""
echo "3. Initialize Firebase Functions:"
echo "   firebase init functions"
echo ""
echo "4. Copy backend code to functions folder and deploy:"
echo "   firebase deploy --only functions"
echo ""

echo "🔧 Option 3: Deploy to Vercel/Netlify (Serverless)"
echo "--------------------------------------------------"
echo "1. Install Vercel CLI:"
echo "   npm install -g vercel"
echo ""
echo "2. Deploy:"
echo "   vercel --prod"
echo ""

echo "🔧 Option 4: Deploy to Railway/Render (PaaS)"
echo "---------------------------------------------"
echo "1. Push code to GitHub"
echo "2. Connect repository to Railway/Render"
echo "3. Set environment variables"
echo "4. Deploy automatically"
echo ""

echo "📝 After Backend Deployment:"
echo "1. Get your backend URL (e.g., https://agent-backend-abc123-uc.a.run.app)"
echo "2. Update frontend environment:"
echo "   VITE_API_URL=https://your-backend-url.com"
echo "3. Rebuild and redeploy frontend"
echo "4. Test the remove functionality"
echo ""

echo "🚨 Important Notes:"
echo "- Set NODE_ENV=production in backend environment"
echo "- Configure CORS to allow your frontend domain"
echo "- Set up proper environment variables for API keys"
echo "- Enable authentication middleware"
echo "- Set up proper Firebase security rules"
echo ""

echo "💡 Need help? Check the logs and ensure all environment variables are set correctly."
